apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: cr.yandex/crp4rlsckt8co5vc0rpu/admin:latest  # не забудь заменить <registry-id>
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://localhost:3000"  # ссылка на backend
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: marketplace
spec:
  type: LoadBalancer
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
